### ISSUE TITLE
Pilot Release

### ISSUE THREAD

**Issue by josefaidt** [josefaidt/amplify-discord-bots#13]
## Todo

- [x] deploy to main env
- [x] sync commands to main env
- [x] ensure commands are functional in sandbox server with local dev
- [x] merge to main
- [x] ensure action redeploys to main
- [x] update interactions endpoint URL in Discord to AppRunner URL
- [x] add to aws-amplify Discord server
- [x] ensure necessary permissions are added (NOTE: `giverole` should be disabled for at-everyone)
- [x] manually modify permissions to `giverole` for mods and admins
- [x] ensure commands are functional in aws-amplify Discord server
- [x] announcement

**Comment by josefaidt** [comment]
![image](https://user-images.githubusercontent.com/5033303/128886389-ad591871-b574-41c4-b44a-2810f4a3be1c.png)

**Comment by josefaidt** [comment]
Bot has been added to the AWS Amplify Discord server and verified command permissions! Closing 🙂
